---
deployment:
  tasks:
    # Set DEPLOYPATH to the webhost [PROJECT] root directory
    - export DEPLOYPATH=/home/stonepla/sail.stoneplayground.com
    # Copy all files recursively to DEPLOYPATH
    - /bin/cp -R * $DEPLOYPATH